name: Create Pull Request

on:
  push:
    branches:
      - main
    paths:
      - 'supported/appids'
      - 'supported/games'

jobs:
  update-version:
    name: Update Version Number
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Version Number
        run: |
          # Initialize the version number if it doesn't exist
          if [ ! -f supported/list_version ]; then
            echo '0' > supported/list_version
          fi
          
          # Increment the version number for each change
          version=$(cat supported/list_version)
          version=$((version + 1))
          echo "$version" > supported/list_version
        working-directory: ${{ github.workspace }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Increment version'
          title: 'Increment version'
          body: 'This PR increments the version number.'

      - name: Get Pull Request URL
        run: |
          echo "Pull Request URL: ${{ steps.cpr.outputs.pull-request-url }}"
