name: Update Number

on:
  push:
    branches:
      - main  # Adjust to your branch name
  workflow_run:
    workflows: ["Check for Changes"]  # Triggered by another workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine if files have changed
        id: check-changes
        run: |
          trigger_files=("supported/appids" "supported/games")
          changed=false

          for file in "${trigger_files[@]}"; do
            if [[ -n $(git diff --name-only origin/main...HEAD "$file") ]]; then
              changed=true
              break
            fi
          done

          echo "::set-output name=trigger_changed::$changed"

      - name: Create file if it doesn't exist
        run: |
          if [ ! -f "supported/list_version" ]; then
            echo "1" > supported/list_version
            git add supported/list_version
            git commit -m "Create list_version file"
            git push
          fi

      - name: Update Number
        if: steps.check-changes.outputs.trigger_changed == 'true'
        run: |
          # Increment the number (you can modify this logic as needed)
          current_number=$(cat supported/list_version)
          new_number=$((current_number + 1))

          # Update the file with the new number
          echo $new_number > supported/list_version
          git add supported/list_version
          git commit -m "Increment number to $new_number"
          git push

