name: Update Version on File Changes

on:
  push:
    paths:
      - 'supported/games'
      - 'supported/appids'

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Run Update Script
        run: |
          chmod +x update_version.sh
          GITHUB_SHA="$GITHUB_SHA" ./update_version.sh
