name: Update List on File Changes

on:
  push:
    paths:
      - 'supported/appids'
      - 'supported/games'

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update List File
      run: |
        # Initialize a counter if it doesn't exist
        if [ ! -f supported/list ]; then
          echo '0' > supported/list
        fi

        # Increment the counter for each change
        counter=$(cat supported/list)
        counter=$((counter + 1))
        echo "$counter" > supported/list

        # Commit and push the changes
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add supported/list
        git commit -m "Increment list counter to $counter"
        git push
      working-directory: ${{ github.workspace }}
